### ISSUE TITLE
P2P text chat

### ISSUE THREAD

**Issue by ARMmaster17** [CS4850Group5A/VirtuDoc#154]

**Comment by PlasAJulian** [comment]
Current error - 
Firefox can’t establish a connection to the server at ws://localhost:8080/chat/609/31hwz1yn/websocket. [websocket.js:6](https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.4.0/lib/transport/browser/websocket.js)
The resource from “http://localhost:8080/login” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by ARMmaster17** [comment]
Does adding `/chat/**` to `SecurityConfig.java` change anything? That's odd that the security config is kicking in because the Spring WebSocket implementation is supposed to work at the Tomcat level where there's no auth middleware.

**Comment by PlasAJulian** [comment]
no its still giving me the same error
